# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name of Person')),
                ('Age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='image', verbose_name='Photos of Person')),
            ],
        ),
    ]
