# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Age',
            new_name='age',
        ),
    ]
