# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0002_auto_20161216_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='personphoto',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fileUpload.Person'),
            preserve_default=False,
        ),
    ]
